### ISSUE TITLE
file '/library/init/data/list/basic.lean' not found in the LEAN_PATH

### ISSUE THREAD

**Issue by girving** [leanprover/theorem_proving_in_lean#15]
I'm getting the above error on https://leanprover.github.io/theorem_proving_in_lean/#03_Propositions_and_Proofs.html.  If I do `Try it yourself` on

    constants p q : Prop

    theorem t1 : p → q → p := λ hp : p, λ hq : q, hp

I get

<img width="847" alt="screen shot 2017-04-08 at 1 33 34 pm" src="https://cloud.githubusercontent.com/assets/70511/24832251/30b501ea-1c60-11e7-9f1e-de4626eb6773.png">

**Comment by girving** [comment]
Browser: Chrome Version 57.0.2987.133 (64-bit)

**Comment by girving** [comment]
The chapters before and after work fine.

**Comment by avigad** [comment]
I am sorry I didn't notice this when it was first opened. It seems to work now. Sometimes pressing the "reload" button fixes problems like this. I'll close this tentatively, but let us know if you still have trouble.
