### ISSUE TITLE
unknown identifier `take`

### ISSUE THREAD

**Issue by williamdemeo** [leanprover/theorem_proving_in_lean#29]
This is only a minor issue/observation.

In Section 4.1 of TPL, there is the following example:

    variables (α : Type) (p q : α → Prop)
    example : (∀ x : α, p x ∧ q x) → ∀ y : α, p y  :=
    assume h : ∀ x : α, p x ∧ q x,
    take y : α,
    show p y, from (h y).left

When I try it in emacs, I get an error at the `take` line: "unknown identifier `take`".  

Where is take defined?  Do I need to load or import some library before trying this example?  (The tutorial doesn't say so.)  

When I try the example in the web browser, it works fine.  And the following alternative version of the same example works fine in emacs:

    variables (α : Type) (p q : α → Prop)
    example : (∀ x : α, p x ∧ q x) → ∀ y : α, p y :=
    λ (h : ∀ x : α, p x ∧ q x) (y : α), and.left (h y)

Unless I'm missing something, perhaps there should be a sentence or two about the `take` command before the example... or you might modify the example to look more like the second version above.

**Comment by robertylewis** [comment]
TPL is based on Lean 3.2 right now. (3.3 was just made official today and the documentation isn't updated yet.) `take` was removed as a keyword between 3.2 and 3.3 since it is redundant; use `assume` instead. https://github.com/leanprover/lean/blob/master/doc/changes.md

**Comment by williamdemeo** [comment]
Great, thanks for the quick answer!  In my next TPL pull request, besides some other typos I found, I'll propose to change `take` to `assume` in the example(s).  Thanks!!

**Comment by avigad** [comment]
Sorry I forgot to close this earlier, but these corrections have been made.

**Comment by williamdemeo** [comment]
Okay, thanks!  I'm closing this now.
