### ISSUE TITLE
Typo in Tutorial

### ISSUE THREAD

**Issue by kevinsullivan** [leanprover/theorem_proving_in_lean#40]
Tutorial (3.3) says,

 "Indeed, in dependent type theory (and in Lean), the Pi construction is fundamental, and α → β is just notation for Π x : α, β when β does not depend on α."

I believe it should say, 

"Indeed, in dependent type theory (and in Lean), the Pi construction is fundamental, and α → β is just notation for Π x : α, β when β does not depend on x."

Difference is in last character before the period.

**Comment by avigad** [comment]
@kevinsullivan Thanks!
