### ISSUE TITLE
...renaming the protected definition nat.induction_on to induction_on.

### ISSUE THREAD

**Issue by holtzermann17** [leanprover/theorem_proving_in_lean#60]
``` lean
open nat (renaming mul → times) (renaming add → plus)
  (hiding succ sub)
```
> ... creates aliases for everything in the nat namespace except succ and sub, renaming nat.add to plus, and renaming the protected definition nat.induction_on to induction_on.

I don't understand the remark about the protected definition.  First of all I don't actually see a definition for `induction_on` anywhere in Lean 3.4.1 -> lean/library/init/data/nat -- but also, there's no explicit renaming of `induction_on` in the code snippet provided.

**Comment by avigad** [comment]
This is a holdover from the past. Lean used to have `induction_on` axioms (same is `induction`, but with a different order of arguments). With some of the newer mechanisms for writing proofs (i.e. with tactics and pattern matching), they became unnecessary. I'll delete it.
