### ISSUE TITLE
Can someone give me a proof that dne -> em?

### ISSUE THREAD

**Issue by technicalguy** [leanprover/theorem_proving_in_lean#67]
In section "3.5 Classical Logic" it says that "As an exercise, you might try proving the converse, that is, showing that em can be proved from dne." Can someone give me a proof of this in Lean without using `open classical`?

**Comment by avigad** [comment]
@technicalguy The appropriate place for questions like this is the Lean chat group, https://leanprover.zulipchat.com/. You'll find a lively community there, happy to answer questions.

In the meanwhile, here is a hint: fill in the two "sorry"'s below.

```lean
axiom dne : ∀ {p : Prop}, ¬ ¬ p → p

example (p : Prop) : p ∨ ¬ p :=
dne $
  assume h₁ : ¬ (p ∨ ¬ p),
  have h₂ : ¬ p, from sorry,
  show false, from sorry
```

**Comment by technicalguy** [comment]
Thanks for directing me to the zulip chat and sorry for asking this question in the wrong place!
